### ISSUE TITLE
User Login/Account Creation

### ISSUE THREAD

**Issue by claire12209** [claire12209/RecipeBook#1]
Actor(s): User
**Description:** Allows for account creation and logging in to access account

**Preconditions:** enter sign-in information or select creating account.

**Basic Flow:** The user enters their username and password which is validated by the password authentication. Or the user selects to create an account and fills out any necessary information for creating an account.

**Alternate Flows:** The user enters their username or password incorrectly, which prints an error message, or the user incorrectly fills in information for creating a new account which also prints an error message.

**Postconditions:** The user has access to their account

Feature 1: Login with Username and Password
•	Scenario 1: Successful login with valid credentials
o	Given the user is on the login page
o	When the user enters their valid username and password
o	Then the system logs the user in and redirects them to their profile page

•	Scenario 2: Login failure due to incorrect password
o	Given the user is on the login page
o	When the user enters an incorrect password
o	Then the system displays an error message indicating that the password is incorrect

•	Scenario 3: Login failure due to non-existent username
o	Given the user is on the login page
o	When the user enters a username that is not registered in the system
o	Then the system displays an error message stating, “Username not found”

**Comment by kaitlyncornish01** [comment]
pushed a working login/registration pages that take you to a profile page.
