### ISSUE TITLE
Search database by category

### ISSUE THREAD

**Issue by claire12209** [claire12209/RecipeBook#4]
**Name**: Search recipe database by category
**Actor(s)**: User
**Description**: Search recipe database by categories of food
**Preconditions**: Entered the search option and select a category of food
**Basic Flow**: The user selects the category of food and then searches the category 
**Alternate Flows**: The category does not exist and an error message is printed 
**Postconditions**: The user can now view recipes stored under that category

User Story 4: As a user, I want to search for recipes by categories so that I can quickly find a specific type of recipe.

Feature 4: Search Recipes by Categories
•	Scenario 1: User searches for recipes by a specific category
o	Given the user is on the recipe search page
o	When the user selects the “Breakfast” category
o	Then the system displays all breakfast recipes available in the database
•	Scenario 2: No recipes found for a category
o	Given the user is on the recipe search page
o	When the user enters the “Vegan Desserts” Category and no recipes are available
o	Then the system displays a message stating, “No recipes found”
•	Scenario 3: User folders recipes by multiple categories
o	Given the user is on the recipe search page
o	When the user selects both “Lunch” and “Vegetarian” categories
o	Then the system displays recipes that fall under both “Lunch” and “Vegetarian” categories

**Comment by kaitlyncornish01** [comment]
I have added this functionality to our project. You can find it in the new branch 'SearchByCategoryAndSearchByIngredients'. The user can now use the filter to filter available recipes by category.
