### ISSUE TITLE
Search by Ingredients

### ISSUE THREAD

**Issue by claire12209** [claire12209/RecipeBook#5]
**Name**: Search recipe database by ingredients
**Actor(s)**: User
**Description**: Search recipe database by entering ingredients 
**Preconditions**: Entered the search option and selected ingredients search
**Basic Flow**: The user selects to search via ingredients list, clicks on ingredients they’d like to include, and recipes that most closely match that ingredients lists appear
**Alternate Flows**: The combination of ingredients does not result in more than ½ the ingredients matched in any recipes, thus the ingredients search returns no matches
**Postconditions**: The user can now access recipes that include the ingredients

User Story 5: As a user, I want to search for recipes by ingredients so that I can find meals I can make with what I have at home.

Feature 5: Search Recipes by Ingredients
•	Scenario 1: User searches for recipes with multiple ingredients
o	Given the user is on the recipe search page
o	When the user enters “chicken” and “broccoli” into the ingredient search bar
o	Then the system displays recipes containing both chicken and broccoli
•	Scenario 2: No results for specific ingredients
o	Given the user is on the recipe search page
o	When the user enters “lobster” and “basil” into the search bar
o	Then the system displays a message indicating no recipes were found.
•	Scenario 3: User searches with a single ingredient
o	Given the user is on the recipe search page
o	When the user enters “tomato” into the ingredient search bar
o	Then the system displays all recipes that include tomato as an ingredient

**Comment by kaitlyncornish01** [comment]
I have added this functionality to our project. You can find it in the new branch 'SearchByCategoryAndSearchByIngredients'. The user can now use the search bar to search for recipes by recipe name or by ingredient used in recipe.
