### ISSUE TITLE
Recipe Reviews

### ISSUE THREAD

**Issue by claire12209** [claire12209/RecipeBook#7]
**Name**: Leave recipe reviews
**Actor(s)**: User
**Description**: leave star rating and comment on recipes
**Preconditions**: selected recipe to review
**Basic Flow**: The user clicks the star corresponding to the rating, and then is able to leave a comment below the recipe
**Alternate Flows**: If the user has already left a review before, ask if they want to review it again. 
**Postconditions**: The user has now left a review that is publicly viewable and linked to their account.

User Story 7: As a user, I want to leave reviews for recipes so that I can share my experience and help other users decide if they want to try the recipe. 

Feature 7: Leave Reviews for Recipes
•	Scenario 1: User successfully leaves a review for a recipe
o	Given the user is logged in and viewing a recipe
o	When the user clicks the “Leave Review” button and submits a review
o	Then the system adds the review to the recipe’s review section
•	Scenario 2: User edits their review
o	Given the user has already left a review for a recipe
o	When the user clicks the “Edit Review” button and submits changes
o	Then the system updates the user’s review with the new content
•	Scenario 3: User deletes their review
o	Given the user has already left a review for a recipe
o	When the user clicks the “Delete Review” button
o	Then the system removes the user’s review from the recipe’s review section

**Comment by kaitlyncornish01** [comment]
I have rating working and it is pushed to branch 'ReviewsAndRatings'.
